version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  test:
    working_directory: ~/repo/openfin-csharp-api-test
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - openfin-tests-packages-{{ .Branch }}
      - run:
          name: "Install project dependencies"
          command: msbuild /t:Restore
      - run:
          name: "Install openfin-cli"
          command: npm install -g openfin-cli
      - run:
          name: "Install OpenfinRVM"
          command: |
            cd C:\Users\circleci\AppData\Local
            mkdir OpenFin
            cd OpenFin
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest -Uri https://developer.openfin.co/release/rvm/latest -OutFile latest.zip
            expand-archive -path .\latest.zip -destinationpath .
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: openfin-tests-packages-{{ .Branch }}
      - run:
          name: "Build"
          command: msbuild /t:Build
      - run:
          name: "Tests"
          command: C:\Users\circleci\.nuget\packages\NUnit.ConsoleRunner\3.11.1\tools\nunit3-console.exe openfin-csharp-api-test.sln
      - save_cache:
          paths:
            - C:\Users\circleci\AppData\Local\OpenFin
          key: openfin-runtimes


workflows:
  version: 2
  main:
    jobs:
      - test
